include hyde.conf

# Minimal Tab bar styling 
tab_bar_edge                bottom
tab_bar_style               powerline
tab_powerline_style         slanted
tab_title_template          {title}{' :{}:'.format(num_windows) if num_windows > 1 else ''}

# Uncomment the following 4 lines to minimize kitty latency (higher energy usage)
input_delay 0
repaint_delay 2
sync_to_monitor no
wayland_enable_ime no

# remap to open new kitty tab in the same directory (default is home dir)
map ctrl+shift+t            new_tab_with_cwd
map ctrl+shift+enter        launch --location=vsplit --cwd=current
map ctrl+shift+b            launch --location=hsplit --cwd=current

# opens yazi in the current path
map ctrl+f send_text all yazi\r

map ctrl+shift+x toggle_layout stack

map ctrl+z scroll_to_prompt -1
map ctrl+x scroll_to_prompt 1

map f2 launch --stdin-source=@last_cmd_output --stdin-add-formatting --type=overlay less +G -R

map ctrl+shift+d launch --location=vsplit dmesg -wH

map ctrl+shift+g launch --stdin-source=@last_visited_cmd_output --type=clipboard

map ctrl+shift+space kitten kitty_grab/grab.py
mouse_map right press ungrabbed mouse_select_command_output
