# Left Monitor (DisplayPort)
monitor=desc:LG Electronics LG IPS FULLHD 201PMZR063837, preferred, 0x0, 1

# Middle Monitor (Standard Desk HDMI)
# Starts at 1920
monitor=desc:LG Electronics LG IPS FULLHD 0x01010101, preferred, 1920x0, 1

# Right Monitor / Laptop (eDP)
# Starts at 3840
monitor=desc:Lenovo Group Limited 0x403D, preferred, 3840x0, 1
