exec-once = clipse --listen 

input {
    touchpad {
        # Enable natural scrolling for touchpad only
        natural_scroll = true
        # Optional: Adjust speed (0.5 is half speed)
        scroll_factor = 0.5 
    }
}


# Fix blur remaining when waybar is hidden
layerrule = ignore_alpha 0, match:namespace waybar

# 1. Enable Variable Frame Rate (Drastically lowers CPU/GPU load when screen is static)
misc {
    disable_hyprland_logo = true
    disable_splash_rendering = true
}

# 2. Disable Blur & Drop Shadows (Huge performance gain on iGPU / Laptop / Nvidia)
decoration {
    shadow {
        enabled = false
    }
    # Set opacities to 1.0 to skip alpha transparency calculations
    active_opacity = 1.0
    inactive_opacity = 1.0
}

# 3. Disable Animations (Instant window switching and zero animation lag)
animations {
    enabled = false
}


