exec-once = clipse --listen
exec-once = swaync
bindd = $mainMod, N, $d toggle notification center, exec, swaync-client -t -sw
bindd = $mainMod Shift, T, $d floating terminal, exec, kitty --class floating-kitty
windowrule = float true, match:class ^(floating-kitty)$
windowrule = size 50% 50%, match:class ^(floating-kitty)$
windowrule = center true, match:class ^(floating-kitty)$

input {
    touchpad {
        # Enable natural scrolling for touchpad only
        natural_scroll = true
        # Optional: Adjust speed (0.5 is half speed)
        scroll_factor = 0.5 
    }
}


# Fix blur remaining when waybar is hidden
layerrule = ignore_alpha 0, match:namespace waybar

# Disable all blur on notifications and swaync layer surfaces
layerrule = blur false, match:namespace ^(notifications|swaync-notification-window|swaync-control-center)$

# 1. Enable Variable Frame Rate (Drastically lowers CPU/GPU load when screen is static)
misc {
    disable_hyprland_logo = true
    disable_splash_rendering = true
}

# 2. Default decoration (normal profile)
decoration {
    blur {
        enabled = true
    }
    shadow {
        enabled = false
    }
}

# 3. Default animations (normal profile)
animations {
    enabled = true
}


