$HOME/.config/kitty/theme.conf|killall -SIGUSR1 kitty
foreground              #FFFFFF
background              #131311
selection_foreground    #131311
selection_background    #FFFFFF
cursor                  #8B6F56
cursor_text_color       #FFFFFF

active_tab_foreground     #131311
active_tab_background     #FFFFFF
inactive_tab_foreground   #FFFFFF
inactive_tab_background   #131311

# black
color0      #181a1c
color8      #828a9a

# red
color1      #ff6578
color9      #ff6578

# green
color2      #9dd274
color10     #9dd274

# yellow
color3      #eacb64
color11     #eacb64

# blue
color4      #72cce8
color12     #72cce8

# magenta
color5      #ba9cf3
color13     #ba9cf3

# cyan
color6      #f69c5e
color14     #f69c5e

# white
color7      #e1e3e4
color15     #ffffff
